# Generated by Django 4.2.7 on 2025-10-01 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHealthMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('database_connections', models.IntegerField(default=0)),
                ('database_query_avg_ms', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('celery_active_tasks', models.IntegerField(default=0)),
                ('celery_pending_tasks', models.IntegerField(default=0)),
                ('celery_failed_tasks_24h', models.IntegerField(default=0)),
                ('blob_storage_usage_gb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('local_storage_usage_gb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('active_user_sessions', models.IntegerField(default=0)),
                ('memory_usage_mb', models.IntegerField(default=0)),
                ('cpu_usage_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('error_rate_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('response_time_avg_ms', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'analytics_system_health_metrics',
                'indexes': [models.Index(fields=['recorded_at'], name='analytics_s_recorde_d45191_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportUsageStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hour', models.IntegerField(blank=True, help_text='Hour of day (0-23)', null=True)),
                ('reports_generated', models.IntegerField(default=0)),
                ('csvs_uploaded', models.IntegerField(default=0)),
                ('reports_downloaded', models.IntegerField(default=0)),
                ('reports_shared', models.IntegerField(default=0)),
                ('avg_csv_size_mb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_processing_time_minutes', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('report_type_breakdown', models.JSONField(default=dict, help_text='Count of reports by type')),
                ('failed_uploads', models.IntegerField(default=0)),
                ('failed_generations', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_report_usage_stats',
                'indexes': [models.Index(fields=['date'], name='analytics_r_date_a75cb0_idx'), models.Index(fields=['date', 'hour'], name='analytics_r_date_0f14ed_idx')],
                'unique_together': {('date', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='DashboardMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Date for these metrics')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='daily', max_length=20)),
                ('total_clients', models.IntegerField(default=0)),
                ('active_clients', models.IntegerField(default=0)),
                ('total_reports', models.IntegerField(default=0)),
                ('reports_generated_today', models.IntegerField(default=0)),
                ('total_recommendations', models.IntegerField(default=0)),
                ('total_potential_savings', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('category_distribution', models.JSONField(default=dict, help_text='Distribution of recommendations by category')),
                ('impact_distribution', models.JSONField(default=dict, help_text='Distribution of recommendations by business impact')),
                ('industry_distribution', models.JSONField(default=dict, help_text='Distribution of clients by industry')),
                ('avg_processing_time_seconds', models.IntegerField(default=0)),
                ('success_rate_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_dashboard_metrics',
                'indexes': [models.Index(fields=['date', 'period_type'], name='analytics_d_date_f24886_idx'), models.Index(fields=['calculated_at'], name='analytics_d_calcula_57c578_idx')],
                'unique_together': {('date', 'period_type')},
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create_client', 'Create Client'), ('update_client', 'Update Client'), ('delete_client', 'Delete Client'), ('upload_csv', 'Upload CSV'), ('generate_report', 'Generate Report'), ('download_report', 'Download Report'), ('share_report', 'Share Report'), ('view_dashboard', 'View Dashboard'), ('other', 'Other')], max_length=30)),
                ('description', models.CharField(help_text='Brief description of the action', max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_user_activity',
                'indexes': [models.Index(fields=['user', 'action'], name='analytics_u_user_id_03db36_idx'), models.Index(fields=['created_at'], name='analytics_u_created_327cd8_idx'), models.Index(fields=['action', 'created_at'], name='analytics_u_action_a2509b_idx')],
            },
        ),
    ]
