# Generated by Django 4.2.7 on 2025-10-01 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(help_text='Client company name', max_length=255)),
                ('industry', models.CharField(choices=[('technology', 'Technology'), ('healthcare', 'Healthcare'), ('finance', 'Finance'), ('education', 'Education'), ('manufacturing', 'Manufacturing'), ('retail', 'Retail'), ('government', 'Government'), ('consulting', 'Consulting'), ('other', 'Other')], default='other', help_text='Client industry sector', max_length=50)),
                ('contact_email', models.EmailField(help_text='Primary contact email', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Primary contact phone', max_length=20)),
                ('contact_person', models.CharField(blank=True, help_text='Primary contact person name', max_length=255)),
                ('azure_subscription_ids', models.JSONField(blank=True, default=list, help_text='List of Azure subscription IDs')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', help_text='Client account status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the client')),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('billing_contact', models.EmailField(blank=True, help_text='Billing contact email', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(choices=[('primary', 'Primary Contact'), ('technical', 'Technical Contact'), ('billing', 'Billing Contact'), ('executive', 'Executive Contact'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(blank=True, help_text='Job title', max_length=100)),
                ('is_primary', models.BooleanField(default=False, help_text='Is this the primary contact?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'client_contacts',
            },
        ),
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_type', models.CharField(choices=[('meeting', 'Meeting'), ('call', 'Phone Call'), ('email', 'Email'), ('issue', 'Issue'), ('opportunity', 'Opportunity'), ('general', 'General')], default='general', max_length=20)),
                ('subject', models.CharField(help_text='Brief subject line', max_length=255)),
                ('content', models.TextField(help_text='Detailed note content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_notes', to='clients.client')),
            ],
            options={
                'db_table': 'client_notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
