# Generated by Django 4.2.7 on 2025-10-01 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientnote',
            name='related_report',
            field=models.ForeignKey(blank=True, help_text='Related report (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.report'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clients.client'),
        ),
        migrations.AddField(
            model_name='client',
            name='account_manager',
            field=models.ForeignKey(blank=True, help_text='Assigned account manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='clientcontact',
            unique_together={('client', 'email')},
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['company_name'], name='clients_company_570f91_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['status'], name='clients_status_98ee60_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['industry'], name='clients_industr_cdecff_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['created_at'], name='clients_created_4c189f_idx'),
        ),
    ]
