# Generated by Django 4.2.7 on 2025-10-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('analyst', 'Analyst'), ('viewer', 'Viewer')], default='analyst', help_text='User role for permission management', max_length=20),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['azure_object_id'], name='auth_user_e_azure_o_ab0d80_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='auth_user_e_email_25b030_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='auth_user_e_role_7f68a6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'role'], name='auth_user_e_is_acti_768bce_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='auth_user_e_created_24e41e_idx'),
        ),
    ]
