# Generated by Django 4.2.7 on 2025-10-01 13:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('detailed', 'Detailed Report'), ('executive', 'Executive Summary'), ('cost', 'Cost Optimization'), ('security', 'Security Assessment'), ('operations', 'Operational Excellence')], help_text='Type of report to generate', max_length=20)),
                ('title', models.CharField(blank=True, help_text='Custom report title (optional)', max_length=255)),
                ('csv_file', models.FileField(blank=True, help_text='Uploaded Azure Advisor CSV file', null=True, upload_to='csv_uploads/%Y/%m/')),
                ('html_file', models.FileField(blank=True, help_text='Generated HTML report file', null=True, upload_to='reports/html/%Y/%m/')),
                ('pdf_file', models.FileField(blank=True, help_text='Generated PDF report file', null=True, upload_to='reports/pdf/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending Upload'), ('uploaded', 'CSV Uploaded'), ('processing', 'Processing CSV'), ('generating', 'Generating Report'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current processing status', max_length=20)),
                ('analysis_data', models.JSONField(blank=True, default=dict, help_text='Processed analytics and metrics from CSV')),
                ('error_message', models.TextField(blank=True, help_text='Error details if processing failed')),
                ('retry_count', models.IntegerField(default=0, help_text='Number of processing retry attempts', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('csv_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('cost', 'Cost'), ('security', 'Security'), ('reliability', 'Reliability'), ('operational_excellence', 'Operational Excellence'), ('performance', 'Performance')], help_text='Recommendation category', max_length=30)),
                ('business_impact', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], help_text='Business impact level', max_length=10)),
                ('recommendation', models.TextField(help_text='Recommendation description')),
                ('subscription_id', models.CharField(blank=True, max_length=255)),
                ('subscription_name', models.CharField(blank=True, max_length=255)),
                ('resource_group', models.CharField(blank=True, max_length=255)),
                ('resource_name', models.CharField(blank=True, max_length=255)),
                ('resource_type', models.CharField(blank=True, max_length=255)),
                ('potential_savings', models.DecimalField(decimal_places=2, default=0, help_text='Potential annual cost savings', max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('potential_benefits', models.TextField(blank=True)),
                ('retirement_date', models.DateField(blank=True, null=True)),
                ('retiring_feature', models.CharField(blank=True, max_length=255)),
                ('advisor_score_impact', models.DecimalField(decimal_places=2, default=0, help_text='Impact on Azure Advisor Score', max_digits=5)),
                ('csv_row_number', models.IntegerField(blank=True, help_text='Original row number in CSV file', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='reports.report')),
            ],
            options={
                'db_table': 'recommendations',
                'ordering': ['-potential_savings', '-advisor_score_impact'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('report_type', models.CharField(choices=[('detailed', 'Detailed Report'), ('executive', 'Executive Summary'), ('cost', 'Cost Optimization'), ('security', 'Security Assessment'), ('operations', 'Operational Excellence')], max_length=20)),
                ('html_template', models.TextField(help_text='HTML template content')),
                ('css_styles', models.TextField(blank=True, help_text='Custom CSS styles')),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_templates',
                'unique_together': {('report_type', 'is_default')},
            },
        ),
        migrations.CreateModel(
            name='ReportShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shared_with_email', models.EmailField(max_length=254)),
                ('permission_level', models.CharField(choices=[('view', 'View Only'), ('download', 'View & Download')], default='view', max_length=20)),
                ('access_token', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('access_count', models.IntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='reports.report')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_shares',
                'unique_together': {('report', 'shared_with_email')},
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['client', 'status'], name='reports_client__80ebc7_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type'], name='reports_report__ff8b25_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_at'], name='reports_created_c5f642_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='reports_status_e83c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['report', 'category'], name='recommendat_report__662bd5_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['business_impact'], name='recommendat_busines_b0d8a4_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['potential_savings'], name='recommendat_potenti_890ab6_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['subscription_id'], name='recommendat_subscri_ebc8e2_idx'),
        ),
    ]
