# Generated by Django 4.2.16 on 2025-01-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_add_azure_integration_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='is_reservation_recommendation',
            field=models.BooleanField(
                default=False,
                help_text='Indicates if this is a reservation/savings plan recommendation'
            ),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='reservation_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('reserved_instance', 'Reserved VM Instance'),
                    ('savings_plan', 'Savings Plan'),
                    ('reserved_capacity', 'Reserved Capacity'),
                    ('other', 'Other Reservation')
                ],
                help_text='Type of reservation or savings plan',
                max_length=50,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='commitment_term_years',
            field=models.IntegerField(
                blank=True,
                choices=[(1, '1 Year'), (3, '3 Years')],
                help_text='Duration of the reservation commitment',
                null=True
            ),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(
                fields=['is_reservation_recommendation'],
                name='recommendat_is_rese_idx'
            ),
        ),
    ]
